/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lootbox.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lootbox.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.LootBox_01_LootBox_02_SG_0.geometry} material={materials.LootBox_02_SG} />
          <mesh geometry={nodes.LootBox_02_LootBox_01_SG_0.geometry} material={materials.LootBox_01_SG} />
          <mesh geometry={nodes.LootBox_03_LootBox_03_SG_0.geometry} material={materials.LootBox_03_SG} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lootbox.gltf')
